# docker image to inherit from
FROM nvcr.io/nvidia/pytorch:20.07-py3
# run linux command
RUN mkdir /root/myservicename
# copy all files to docker container
COPY . /root/myservicename
# set working directory
WORKDIR /root/myservicename

# upgrade pip, install grpcio and grpcio-tools
# remove cache and other stuff (keep docker image as small as possible)
# then COMPILE PROTO FILE (IMPORTANT!)
RUN python -m pip --no-cache-dir install --upgrade pip grpcio grpcio-tools && \
    ldconfig && \
    rm -rf /tmp/* /workspace/* && \
    python -m grpc.tools.protoc -I. --python_out . --grpc_python_out . ./myservice.proto

# port number to expose
EXPOSE 35015

ENTRYPOINT ["python", "myservice_server.py"]
