# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: image_classification_service.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fmyservice.proto\"\x1a\n\x07MyInput\x12\x0f\n\x07mystrin\x18\x01 \x01(\t\"\x1c\n\x08MyOutput\x12\x10\n\x08mystrout\x18\x01 \x01(\t28\n\rMyServiceName\x12\'\n\x10MyRequestHandler\x12\x08.MyInput\x1a\t.MyOutputb\x06proto3')



_MYINPUT = DESCRIPTOR.message_types_by_name['MyInput']
_MYOUTPUT = DESCRIPTOR.message_types_by_name['MyOutput']
MyInput = _reflection.GeneratedProtocolMessageType('MyInput', (_message.Message,), {
  'DESCRIPTOR' : _MYINPUT,
  '__module__' : 'myservice_pb2'
  # @@protoc_insertion_point(class_scope:MyInput)
  })
_sym_db.RegisterMessage(MyInput)

MyOutput = _reflection.GeneratedProtocolMessageType('MyOutput', (_message.Message,), {
  'DESCRIPTOR' : _MYOUTPUT,
  '__module__' : 'myservice_pb2'
  # @@protoc_insertion_point(class_scope:MyOutput)
  })
_sym_db.RegisterMessage(MyOutput)

_MYSERVICENAME = DESCRIPTOR.services_by_name['MyServiceName']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _MYINPUT._serialized_start=19
  _MYINPUT._serialized_end=45
  _MYOUTPUT._serialized_start=47
  _MYOUTPUT._serialized_end=75
  _MYSERVICENAME._serialized_start=77
  _MYSERVICENAME._serialized_end=133
# @@protoc_insertion_point(module_scope)
