# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import myservice_pb2 as myservice__pb2


class MyServiceNameStub(object):
    """service nickname
    rpc: input output configuration
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.MyRequestHandler = channel.unary_unary(
                '/MyServiceName/MyRequestHandler',
                request_serializer=myservice__pb2.MyInput.SerializeToString,
                response_deserializer=myservice__pb2.MyOutput.FromString,
                )


class MyServiceNameServicer(object):
    """service nickname
    rpc: input output configuration
    """

    def MyRequestHandler(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MyServiceNameServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'MyRequestHandler': grpc.unary_unary_rpc_method_handler(
                    servicer.MyRequestHandler,
                    request_deserializer=myservice__pb2.MyInput.FromString,
                    response_serializer=myservice__pb2.MyOutput.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'MyServiceName', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class MyServiceName(object):
    """service nickname
    rpc: input output configuration
    """

    @staticmethod
    def MyRequestHandler(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/MyServiceName/MyRequestHandler',
            myservice__pb2.MyInput.SerializeToString,
            myservice__pb2.MyOutput.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
