#!/bin/bash
# echo name of script is $0
# echo first argument is $1
# echo second argument is $2
# echo seventeenth argument is $17
# echo number of arguments is $#

# clear ## uncomment if you want to clear the screen

javac $1.java
if [ $? != 0 ]; then
{
	echo
	echo "Your code did not compile. Debug it and try again."
}
else
{
	echo
	java $1
}
fi
echo
